// Main exports for all components
export { Navigation } from './Navigation';
export { HeroSection } from './HeroSection';
export { AboutSection } from './AboutSection';
export { ServicesSection } from './ServicesSection';
export { ProjectsSection } from './ProjectsSection';
export { TestimonialsSection } from './TestimonialsSection';
export { ContactSection } from './ContactSection';
export { Footer } from './Footer';
